services:
  - type: web
    name: constructtrack
    env: node
    region: singapore
    buildCommand: cd frontend && npm ci && npm run build && cd ../backend && npm ci --omit=dev
    startCommand: cd backend && node server.js
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        value: ct-pro-52457423da7754545930fc5779faf99ce505169a04da0d85ae711232d53db845
      - key: DATABASE_URL
        value: postgresql://constructtracker_user:HRQbLhR8YXwCsVrxEUUCJSvOJWNMXyZI@dpg-da9v6fu7bikc73f05e90-a.oregon-postgres.render.com/constructtracker
      - key: PUBLIC_DIR
        value: ../frontend/dist
