services:
  - type: web
    name: constructtrack
    env: node
    region: singapore
    buildCommand: cd frontend && npm ci && npm run build && cd ../backend && npm ci --omit=dev
    startCommand: cd backend && node server.js
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        value: ct-pro-52457423da7754545930fc5779faf99ce505169a04da0d85ae711232d53db845
      - key: DATABASE_URL
        value: postgresql://todo_app_nr3k_user:MQoEbP97Irh60OJfF1HdLsMgKvdplLnm@dpg-d8vc43ugvqtc73c2ov70-a.oregon-postgres.render.com:5432/constructtrack?sslmode=require
      - key: PUBLIC_DIR
        value: ../frontend/dist
